# Generated by Django 4.2.5 on 2024-02-21 21:46

import comintapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComintUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='last name')),
                ('display_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='display name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'auth_user',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LineOfCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('avatar_url', models.CharField(blank=True, max_length=256, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('ssn', models.CharField(blank=True, help_text='Social Security Number in the format XXX-XX-XXXX', max_length=11, null=True, validators=[comintapp.models.validate_ssn], verbose_name='SSN (optional)')),
                ('address_1', models.CharField(max_length=255, verbose_name='Address 1')),
                ('address_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address 2')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('consent_for_verification', models.BooleanField(default=False, verbose_name='Consent for Identity Verification')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Profile Completed')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='VerificationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('childhood_nickname', 'What was your childhood nickname?'), ('favorite_childhood_friend', 'What is the name of your favorite childhood friend?'), ('parents_meet_city', 'In what city or town did your mother and father meet?'), ('favorite_team', 'What is your favorite team?'), ('dream_job_child', 'What was your dream job as a child?'), ('first_car_make_model', 'What was the make and model of your first car?'), ('hospital_born', 'What was the name of the hospital where you were born?'), ('childhood_sports_hero', 'Who is your childhood sports hero?'), ('mothers_maiden_name', 'What was your mother’s maiden name?')], max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LOCNegotiationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(help_text='Term in months')),
                ('interest_rate', models.DecimalField(decimal_places=1, help_text='Interest rate as a percentage', max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Loan amount in USD', max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COUNTERED', 'Countered'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('line_of_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='comintapp.lineofcredit')),
                ('request_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc_negotiations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LOCConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('loc_negotiation_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='comintapp.locnegotiationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(help_text='Term in months')),
                ('interest_rate', models.DecimalField(decimal_places=1, help_text='Interest rate as a percentage', max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Loan amount in USD', max_digits=6)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('EXPIRING', 'Expiring'), ('EXPIRED', 'Expired'), ('FUNDED', 'Funded'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lineofcredit',
            name='loan_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines_of_credit', to='comintapp.loanrequest'),
        ),
        migrations.AddField(
            model_name='lineofcredit',
            name='negotiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiated_loc', to=settings.AUTH_USER_MODEL),
        ),
    ]
