# Generated by Django 4.2.5 on 2024-02-21 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comintapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locnegotiationrequest',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
