# Generated by Django 4.2.5 on 2023-10-16 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comintapp', '0002_remove_comintuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comintuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='comintuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='comintuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='comintuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='comintuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='comintuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='comintuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='last name'),
        ),
    ]
