# Generated by Django 4.2.5 on 2024-02-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comintapp', '0002_locnegotiationrequest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locnegotiationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
