# Generated by Django 4.2.5 on 2023-10-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comintapp', '0003_comintuser_display_name_alter_comintuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comintuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='comintuser',
            table='auth_user',
        ),
    ]
