# Generated by Django 4.2.5 on 2023-11-20 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comintapp', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('childhood_nickname', 'What was your childhood nickname?'), ('favorite_childhood_friend', 'What is the name of your favorite childhood friend?'), ('parents_meet_city', 'In what city or town did your mother and father meet?'), ('favorite_team', 'What is your favorite team?'), ('dream_job_child', 'What was your dream job as a child?'), ('first_car_make_model', 'What was the make and model of your first car?'), ('hospital_born', 'What was the name of the hospital where you were born?'), ('childhood_sports_hero', 'Who is your childhood sports hero?'), ('mothers_maiden_name', 'What was your mother’s maiden name?')], max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
