# Generated by Django 4.2.5 on 2023-11-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comintapp', '0006_verificationquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_1',
            field=models.CharField(default='', max_length=255, verbose_name='Address 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address 2'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent_for_verification',
            field=models.BooleanField(default=False, verbose_name='Consent for Identity Verification'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(default='AZ', max_length=100, verbose_name='State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(default='00000', max_length=10, verbose_name='Zip Code'),
            preserve_default=False,
        ),
    ]
