# Generated by Django 4.2.5 on 2024-02-03 02:53

import comintapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comintapp', '0007_userprofile_address_1_userprofile_address_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Profile Completed'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ssn',
            field=models.CharField(help_text='Social Security Number in the format XXX-XX-XXXX', max_length=11, validators=[comintapp.models.validate_ssn], verbose_name='SSN (optional)'),
        ),
    ]
