# Generated by Django 4.2.5 on 2024-02-03 03:09

import comintapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comintapp', '0008_userprofile_is_complete_alter_userprofile_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ssn',
            field=models.CharField(blank=True, help_text='Social Security Number in the format XXX-XX-XXXX', max_length=11, null=True, validators=[comintapp.models.validate_ssn], verbose_name='SSN (optional)'),
        ),
    ]
