# Generated by Django 4.2.5 on 2024-02-03 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comintapp', '0009_alter_userprofile_ssn'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineOfCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LOCNegotiationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(help_text='Term in months')),
                ('interest_rate', models.DecimalField(decimal_places=1, help_text='Interest rate as a percentage', max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Loan amount in USD', max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COUNTERED', 'Countered'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('line_of_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='comintapp.lineofcredit')),
                ('request_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc_negotiations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LOCConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('loc_negotiation_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='comintapp.locnegotiationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(help_text='Term in months')),
                ('interest_rate', models.DecimalField(decimal_places=1, help_text='Interest rate as a percentage', max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Loan amount in USD', max_digits=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('EXPIRING', 'Expiring'), ('EXPIRED', 'Expired'), ('FUNDED', 'Funded'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lineofcredit',
            name='loan_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines_of_credit', to='comintapp.loanrequest'),
        ),
        migrations.AddField(
            model_name='lineofcredit',
            name='negotiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiated_loc', to=settings.AUTH_USER_MODEL),
        ),
    ]
